CREATE TABLE IF NOT EXISTS devices (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  maximum_consumption DOUBLE PRECISION NOT NULL,
  user_id BIGINT,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);